import { IBooks } from './interfaces';

export const BOOKS: IBooks = [
  // JavaScript
  {
    category: 'javascript',
    name: 'Eloquent Javascript A Modern Introduction to Programming',
    author: 'Marijn Haverbeke',
    year: '2018',
    pages: '447',
    format: 'PDF',
    downloadLink: 'https://bit.ly/35wKZPF',
    buyLink: 'https://amzn.to/3bSNm0l',
    description: 'Eloquent JavaScriptdives into the JavaScript language to show programmers how to write elegant, effective JavaScript code. Like any good programming book,Eloquent JavaScriptbegins with fundamentals--variables, control structures, functions, and data structures--then moves on to complex topics like object-oriented programming and regular expressions',
    image: 'https://covers.zlibcdn2.com/covers299/books/e0/16/5a/e0165acb1767639826cf43eb5fab00e9.jpg',
  },
  {
    category: 'javascript',
    name: 'Learning JavaScript Design Patterns',
    author: 'Addy Osmani',
    year: '2012',
    pages: '199',
    format: 'PDF',
    downloadLink: 'https://bit.ly/2Zt7bq7',
    buyLink: 'https://amzn.to/3khG0X1',
    description: 'If you want to write beautiful, structured, and maintainable javascript code, this guide shows you how to apply both classical and modern design patterns to the language. The patterns in this book provide reusable code solutions to common problems in software design, and give you a shared vocabulary for describing solutions to others',
    image: 'https://covers.zlibcdn2.com/covers299/books/08/f6/16/08f6168945c836449f3e40e6c170ad67.jpg',
  },
  // JavaScript

  // Java
  {
    category: 'java',
    name: 'Java: The Complete Reference, Eleventh Edition',
    author: 'Herbert Schildt',
    year: '2019',
    pages: '1882',
    format: 'PDF',
    downloadLink: 'https://bit.ly/2RzMTXL',
    buyLink: 'https://amzn.to/35s1ZXk',
    description: 'Fully updated for Java SE 11, Java: The Complete Reference, Eleventh Edition explains how to develop, compile, debug, and run Java programs. Best-selling programming author Herb Schildt covers the entire Java language, including its syntax, keywords, and fundamental programming principles. You’ll also find information on key portions of the Java API library, such as I/O, the Collections Framework, the stream library, and the concurrency utilities. Swing, JavaBeans, and servlets are examined and numerous examples demonstrate Java in action. Of course, the very important module system is discussed in detail. This Oracle Press resource also offers an introduction to JShell, Java’s interactive programming tool. Best of all, the book is written in the clear, crisp, uncompromising style that has made Schildt the choice of millions worldwide.',
    image: 'https://covers.zlibcdn2.com/covers299/books/7f/b0/e5/7fb0e58e87aef95feae8c9d3a986a0a7.jpg',
  },
  {
    category: 'java',
    name: 'Head First Java, 2nd Edition',
    author: 'Kathy Sierra',
    year: '2005',
    pages: '722',
    format: 'PDF',
    downloadLink: 'https://bit.ly/3kbsSTu',
    buyLink: 'https://amzn.to/3misNze',
    description: 'Learning a complex new language is no easy task especially when it s an object-oriented computer programming language like Java. You might think the problem is your brain. It seems to have a mind of its own, a mind that doesn\'t always want to take in the dry, technical stuff you\'re forced to study. The fact is your brain craves novelty. It\'s constantly searching, scanning, waiting for something unusual to happen',
    image: 'https://covers.zlibcdn2.com/covers299/books/d5/be/db/d5bedbe6b001445ebb3851500fd19fb3.jpg',
  },
  {
    category: 'java',
    name: 'Java for Absolute Beginners',
    author: 'Iuliana Cosmina',
    year: '2019',
    pages: '623',
    format: 'PDF',
    downloadLink: 'https://bit.ly/2RnxwkY',
    buyLink: 'https://amzn.to/2Zu4m88',
    description: 'Write your first code in Java using simple, step-by-step examples that model real-word objects and events, making learning easy. With this book you’ll be able to pick up the concepts without fuss. Java for Absolute Beginners teaches Java development in language anyone can understand, giving you the best possible start. You’ll see clear code descriptions and layout so that you can get your code running as soon as possible. After reading this book, you\'ll come away with the basics to get started writing programs in Java.',
    image: 'https://covers.zlibcdn2.com/covers299/books/0d/b0/f2/0db0f2eae168c600917807d193abdf4a.jpg',
  },
  // Java

  // Python
  {
    category: 'python',
    name: 'Python Basics: A Self-Teaching Introduction',
    author: 'H. Bhasin',
    year: '2019',
    pages: '566',
    format: 'PDF',
    downloadLink: 'https://bit.ly/3kd9c1p',
    buyLink: 'https://amzn.to/2FpLQab',
    description: 'This book is designed for use as a primary introduction to Python and can be used as an introductory text or as a resource for professionals in industry. The book has been divided into four sections. The first section deals with the language fundamentals, primarily the procedural part of the language, the second introduces the object-oriented paradigms, the third section deals with data structures, and the last is devoted to advanced topics like handling multi-dimensional arrays using NumPy and visualization using Matplotlib. Regular expressions and multi-threading have been introduced in the appendices.',
    image: 'https://covers.zlibcdn2.com/covers299/books/f0/d3/6d/f0d36d571089b7f21c8e4a117b0440f5.jpg',
  },
  {
    category: 'python',
    name: 'Learning Python, 5th Edition',
    author: 'Mark Lutz',
    year: '2013',
    pages: '1600',
    format: 'PDF',
    downloadLink: 'https://bit.ly/33i8b1a',
    buyLink: 'https://amzn.to/2ZxQ4Dn',
    description: 'Get a comprehensive, in-depth introduction to the core Python language with this hands-on book. Based on author Mark Lutz’s popular training course, this updated fifth edition will help you quickly write efficient, high-quality code with Python. It’s an ideal way to begin, whether you’re new to programming or a professional developer versed in other languages.',
    image: 'https://covers.zlibcdn2.com/covers299/books/2e/3b/7c/2e3b7c8e0d2f4d71d4b0753f62458ff1.jpg',
  },
  // Python

  // SQL
  {
    category: 'sql',
    name: 'SQL for Dummies',
    author: 'Allen G. Taylor',
    year: '2019',
    pages: '515',
    format: 'PDF',
    downloadLink: 'https://bit.ly/3kbnZd4',
    buyLink: 'https://amzn.to/2ZzQIjP',
    description: 'SQL is the international standard database language used to create, access, manipulate, maintain, and store information in relational database management systems (DBMS) such as Access, Oracle, SQL Server, and MySQL. SQL adds powerful data manipulation and retrieval capabilities to conventional languages—and this book shows you how to harness the core element of relational databases with ease.',
    image: 'https://covers.zlibcdn2.com/covers299/books/6f/b8/d8/6fb8d87d7fb4865674245ff408354bda.jpg',
  },
  {
    category: 'sql',
    name: 'Practical SQL: A Beginner’s Guide to Storytelling with Data',
    author: 'DeBarros Anthony',
    year: '2018',
    pages: '527',
    format: 'PDF',
    downloadLink: 'https://bit.ly/3hsCYO7',
    buyLink: 'https://amzn.to/3irlAdD',
    description: 'Practical SQL is an approachable and fast-paced guide to SQL (Structured Query Language), the standard programming language for defining, organizing, and exploring data in relational databases. The book focuses on using SQL to find the story your data tells, with the popular open-source database PostgreSQL and the pgAdmin interface as its primary tools',
    image: 'https://covers.zlibcdn2.com/covers299/books/b9/a9/b7/b9a9b788cf8f7b2d0888aa414462373e.jpg',
  },
  // SQL

  // Data structure & Algorithms
  {
    category: 'data structure & algorithms',
    name: 'Introduction to algorithms',
    author: 'Thomas Cormen',
    year: '2009',
    pages: '1313',
    format: 'PDF',
    downloadLink: 'https://bit.ly/35wua7r',
    buyLink: 'https://amzn.to/2GMON4T',
    description: 'In the preface, the authors write about how the book was written to be comprehensive and useful in both teaching and professional environments. Each chapter focuses on an algorithm, and discusses its design techniques and areas of application. Instead of using a specific programming language, the algorithms are written in pseudocode. The descriptions focus on the aspects of the algorithm itself, its mathematical properties, and emphasize efficiency',
    image: 'https://covers.zlibcdn2.com/covers299/books/ed/37/2a/ed372ab968c3d988e0490962553aa3cf.jpg',
  },
  {
    category: 'data structure & algorithms',
    name: 'The Algorithm Design Manual',
    author: 'Thomas Cormen',
    year: '2013',
    pages: '237',
    format: 'PDF',
    downloadLink: 'https://bit.ly/33pOXH5',
    buyLink: 'https://amzn.to/2DULDej',
    description: 'Have you ever wondered how your GPS can find the fastest way to your destination, selecting one route from seemingly countless possibilities in mere seconds? How your credit card account number is protected when you make a purchase over the Internet? The answer is algorithms. And how do these mathematical formulations translate themselves into your GPS, your laptop, or your smart phone? This book offers an engagingly written guide to the basics of computer algorithms. In Algorithms Unlocked, Thomas Cormen―coauthor of the leading college textbook on the subject―provides a general explanation, with limited mathematics, of how algorithms enable computers to solve problems.',
    image: 'https://covers.zlibcdn2.com/covers299/books/de/d6/55/ded655a8c87eda65c81f064aade1f901.jpg',
  },
  {
    category: 'data structure & algorithms',
    name: 'The Algorithm Design Manual',
    author: 'Steven S. Skiena',
    year: '2008',
    pages: '730',
    format: 'PDF',
    downloadLink: 'https://bit.ly/2RlWscr',
    buyLink: 'https://amzn.to/3kq8mPh',
    description: 'The reader-friendly Algorithm Design Manual provides straightforward access to combinatorial algorithms technology, stressing design over analysis. The first part, Techniques, provides accessible instruction on methods for designing and analyzing computer algorithms. The second part, Resources, is intended for browsing and reference, and comprises the catalog of algorithmic resources, implementations and an extensive bibliography.',
    image: 'https://covers.zlibcdn2.com/covers299/books/00/cb/81/00cb810a4b852c9631b47fb6de8efad0.jpg',
  },
  {
    category: 'data structure & algorithms',
    name: 'Algorithms: Part II, 4th Edition',
    author: 'Robert Sedgewick',
    year: '2014',
    pages: '950',
    format: 'PDF',
    downloadLink: 'https://bit.ly/3mkq2xa',
    buyLink: 'https://amzn.to/35AlQ6C',
    description: 'The reader-friendly Algorithm Design Manual provides straightforward access to combinatorial algorithms technology, stressing design over analysis. The first part, Techniques, provides accessible instruction on methods for designing and analyzing computer algorithms. The second part, Resources, is intended for browsing and reference, and comprises the catalog of algorithmic resources, implementations and an extensive bibliography.',
    image: 'https://covers.zlibcdn2.com/covers299/books/d3/07/7a/d3077abbf3e55579b7973d04da812939.jpg',
  },
  {
    category: 'data structure & algorithms',
    name: 'Data Structures & Algorithms in Java',
    author: 'Robert Lafore',
    year: '1998',
    pages: '526',
    format: 'PDF',
    downloadLink: 'https://bit.ly/3k8rgcY',
    buyLink: 'https://amzn.to/35w62lj',
    description: 'Not filled with with obtuse mathematics and difficult proofs, MWSS:Data Structures and Algorithms in Java removes the mystique from DS&A. It does this in two ways. First, the text is written in a straightforward style, making it accessible to anyone. Second, unique new Java demonstration programs, called "Workshop Applets," are provided with the book',
    image: 'https://covers.zlibcdn2.com/covers299/books/50/aa/05/50aa051a399071ca6ac7e837fb7f1be8.jpg',
  },
  // Data structure & Algorithms

  // Architecture
  {
    category: 'architecture',
    name: 'Clean Architecture: A Craftsman’s Guide to Software Structure and Design',
    author: 'Robert C. Martin',
    year: '2017',
    pages: '429',
    format: 'PDF',
    downloadLink: 'https://bit.ly/2Zw1uaI',
    buyLink: 'https://amzn.to/2Fv5e5h',
    description: 'Building upon the success of best-sellers The Clean Coder and Clean Code, legendary software craftsman Robert C. "Uncle Bob" Martin shows how to bring greater professionalism and discipline to application architecture and design.',
    image: 'https://covers.zlibcdn2.com/covers299/books/b1/c9/42/b1c94251908069df0a3dbe2462f52cdd.jpg',
  },
  {
    category: 'architecture',
    name: 'Computer Architecture, Sixth Edition: A Quantitative Approach',
    author: 'David A. Patterson',
    year: '2017',
    pages: '936',
    format: 'PDF',
    downloadLink: 'https://bit.ly/3mh2tWb',
    buyLink: 'https://amzn.to/3ir5Do7',
    description: 'Computer Architecture: A Quantitative Approach, Sixth Edition has been considered essential reading by instructors, students and practitioners of computer design for over 20 years. The sixth edition of this classic textbook is fully revised with the latest developments in processor and system architecture. It now features examples from the RISC-V (RISC Five) instruction set architecture, a modern RISC instruction set developed and designed to be a free and openly adoptable standard. It also includes a new chapter on domain-specific architectures and an updated chapter on warehouse-scale computing that features the first public information on Google\'s newest WSC.',
    image: 'https://covers.zlibcdn2.com/covers299/books/58/73/4d/58734dae75228cd8ccf1be995da2893a.jpg',
  },
  // Architecture

  // Design patterns
  {
    category: 'design patterns',
    name: 'Head First Design Patterns',
    author: 'Eric Freeman',
    year: '2014',
    pages: '867',
    format: 'PDF',
    downloadLink: 'https://bit.ly/3ms9WBY',
    buyLink: 'https://amzn.to/2DWsCYZ',
    description: 'At any given moment, someone struggles with the same software design problems you have. And, chances are, someone else has already solved your problem. This edition of Head First Design Patterns—now updated for Java 8—shows you the tried-and-true, road-tested patterns used by developers to create functional, elegant, reusable, and flexible software. By the time you finish this book, you’ll be able to take advantage of the best design practices and experiences of those who have fought the beast of software design and triumphed.',
    image: 'https://covers.zlibcdn2.com/covers299/books/8c/26/dc/8c26dcd40152ee5088314b1c62db48cb.jpg',
  },
  {
    category: 'design patterns',
    name: 'Building Structures Illustrated: Patterns, Systems, and Design',
    author: 'Francis D. K. Ching',
    year: '2013',
    pages: '354',
    format: 'PDF',
    downloadLink: 'https://bit.ly/3mlLrX8',
    buyLink: 'https://amzn.to/3hrEeRF',
    description: 'Structures are an essential element of the building process, yet one of the most difficult concepts for architects to grasp. While structural engineers do the detailed consulting work for a project, architects should have enough knowledge of structural theory and analysis to design a building. Building Structures Illustrated takes a new approach to structural design, showing how structural systems of a building—such as an integrated assembly of elements with pattern, proportions, and scale—are related to the fundamental aspects of architectural design',
    image: 'https://covers.zlibcdn2.com/covers299/books/cb/b2/f6/cbb2f6cc498af0a2ae57e5be6716758b.jpg',
  },
  // Design patterns

  // Networks
  {
    category: 'networks',
    name: 'Networks',
    author: 'Mark Newman',
    year: '2018',
    pages: '800',
    format: 'PDF',
    downloadLink: 'https://bit.ly/35wwMSN',
    buyLink: 'https://amzn.to/2RlY99T',
    description: 'The study of networks, including computer networks, social networks, and biological networks, has attracted enormous interest in the last few years. The rise of the Internet and the wide availability of inexpensive computers have made it possible to gather and analyze network data on an unprecedented scale, and the development of new theoretical tools has allowed us to extract knowledge from networks of many different kinds. The study of networks is broadly interdisciplinary and central developments have occurred in many fields, including mathematics, physics, computer and information sciences, biology, and the social sciences. This book brings together the most important breakthroughs in each of these fields and presents them in a coherent fashion, highlighting the strong interconnections between work in different areas.',
    image: 'https://covers.zlibcdn2.com/covers299/books/52/26/dd/5226dd61a8e53e82d123f4831acaf53b.jpg',
  },
  {
    category: 'networks',
    name: 'Computer Networking: A Top-Down Approach',
    author: 'Keith Ross',
    year: '2016',
    pages: '864',
    format: 'PDF',
    downloadLink: 'https://bit.ly/35vY8IP',
    buyLink: 'https://amzn.to/3msaxnc',
    description: 'Unique among computer networking texts, the Seventh Edition of the popular Computer Networking: A Top Down Approach builds on the author’s long tradition of teaching this complex subject through a layered approach in a “top-down manner.” The text works its way from the application layer down toward the physical layer, motivating readers by exposing them to important concepts early in their study of networking',
    image: 'https://covers.zlibcdn2.com/covers299/books/25/b0/96/25b0960fd42a492a64082880678a76af.jpg',
  },
  {
    category: 'networks',
    name: 'Computer Networks',
    author: 'Andrew Tanenbaum',
    year: '2013',
    pages: '962',
    format: 'PDF',
    downloadLink: 'https://bit.ly/33rE5Z9',
    buyLink: 'https://amzn.to/2ZzZ0rX',
    description: 'Tanenbaum takes a structured approach to explaining how networks work from the inside out. He starts with an explanation of the physical layer of networking, computer hardware and transmission systems; then works his way up to network applications. Tanenbaum\'s in-depth application coverage includes email; the domain name system; the World Wide Web (both client- and server-side); and multimedia (including voice over IP, Internet radio video on demand, video conferencing, and streaming media. Each chapter follows a consistent approach: Tanenbaum presents key principles, then illustrates them utilizing real-world example networks that run through the entire book—the Internet, and wireless networks, including Wireless LANs, broadband wireless and Bluetooth. The Fifth Edition includes a chapter devoted exclusively to network security. The textbook is supplemented by a Solutions Manual, as well as a Website containing PowerPoint slides, art in various forms, and other tools for instruction, including a protocol simulator whereby students can develop and test their own network protocols.',
    image: 'https://covers.zlibcdn2.com/covers299/books/c4/22/89/c422893549f0d1733d7d10daeb41f3bd.jpg',
  },
  // Networks

  // Information Systems
  {
    category: 'information systems',
    name: 'Management Information Systems: Managing the Digital Firm',
    author: 'Kenneth C. Laudon',
    year: '2019',
    pages: '660',
    format: 'PDF',
    downloadLink: 'https://bit.ly/2Rk6Z8b',
    buyLink: 'https://amzn.to/3mh5oOD',
    description: 'The authoritative, case-based study of IS in business today Management Information Systems: Managing the Digital Firm provides the most comprehensive overview of information systems used by business firms today, while drawing connections between MIS and business performance',
    image: 'https://covers.zlibcdn2.com/covers299/books/e1/34/c5/e134c58e6354f42a8dd498f1ea33ce10.jpg',
  },
  {
    category: 'information systems',
    name: 'Learning Agile: Understanding Scrum, XP, Lean, and Kanban',
    author: 'Andrew Stellman',
    year: '2014',
    pages: '420',
    format: 'PDF',
    downloadLink: 'https://bit.ly/2Fjk2o2',
    buyLink: 'https://amzn.to/3bSqH48',
    description: 'Agile has revolutionized the way teams approach software development, but with dozens of agile methodologies to choose from, the decision to "go agile" can be tricky. This practical book helps you sort it out, first by grounding you in agile’s underlying principles, then by describing four specific—and well-used—agile methods: Scrum, extreme programming (XP), Lean, and Kanban.',
    image: 'https://covers.zlibcdn2.com/covers299/books/24/79/f9/2479f9e08e9b3d454fa6791f58c174b6.jpg',
  },
  {
    category: 'information systems',
    name: 'Blockchain: Ultimate guide to understanding blockchain, bitcoin, cryptocurrencies, smart contracts and the future of money.',
    author: 'Mark Gates',
    year: '2017',
    pages: '125',
    format: 'PDF',
    downloadLink: 'https://bit.ly/32qbaFK',
    buyLink: 'https://amzn.to/33q3T81',
    description: '“On the internet, nobody knows you’re a dog.” - Peter Steiner On the blockchain, nobody knows you’re a fridge.” - Richard Gendal Brown Blockchain technology has been called the greatest innovation since the internet',
    image: 'https://covers.zlibcdn2.com/covers299/books/cd/42/16/cd4216e2f6cbba006e935566acd3e2c1.jpg',
  },
  // Information Systems

  // Operating systems
  {
    category: 'operating systems',
    name: 'Structured Computer Organization.',
    author: 'Andrew S. Tanenbaum',
    year: '2012',
    pages: '801',
    format: 'PDF',
    downloadLink: 'https://bit.ly/3isNfuO',
    buyLink: 'https://amzn.to/3iv17F8',
    description: 'Structured Computer Organization, specifically written for undergraduate students, is a best-selling guide that provides an accessible introduction to computer hardware and architecture. This text will also serve as a useful resource for all computer professionals and engineers who need an overview or introduction to computer architecture',
    image: 'https://covers.zlibcdn2.com/covers299/books/0c/37/9a/0c379a31a38988e576779d2531b5dc3c.jpg',
  },
  {
    category: 'operating systems',
    name: 'Modern Operating Systems.',
    author: 'Andrew S. Tanenbaum',
    year: '2014',
    pages: '1137',
    format: 'PDF',
    downloadLink: 'https://bit.ly/32qFxfl',
    buyLink: 'https://amzn.to/3kjosdr',
    description: 'Modern Operating Systems, Fourth Edition, is intended for introductory courses in Operating Systems in Computer Science, Computer Engineering, and Electrical Engineering programs. It also serves as a useful reference for OS professionals',
    image: 'https://covers.zlibcdn2.com/covers299/books/15/6c/f9/156cf9f53cc80458097cebf1876be746.jpg',
  },
  // Operating systems
];
