import { ICategories } from './interfaces';

export const CATEGORIES: ICategories[] = [
  {
    name: 'Programming',
    icon: '../assets/images/categories/programming.png',
    showSubCategories: false,
    subCategories: [
      'JavaScript',
      'Java',
      'Python',
      'SQL',
      'Data structure & Algorithms',
      'Architecture',
      'Design Patterns',
      'Networks',
      'Information Systems',
      'Operating systems',
    ],
  },
  {
    name: 'Business',
    icon: '../assets/images/categories/business.png',
    showSubCategories: false,
    subCategories: [
      'Management',
      'Marketing',
      'Accounting',
      'Investing',
      'Markets',
      'Econometrics',
    ],
  },
  {
    name: 'Mathematics',
    icon: '../assets/images/categories/mathematics.png',
    showSubCategories: false,
    subCategories: [
      'Algebra',
      'Linear Algebra',
      'Discrete Mathematics',
      'Number Theory',
      'Operator Theory',
      'Graph Theory',
      'Computer Algebra',
      'Analysis',
      'Mathematicsematical Statistics',
  ],
  },
  {
    name: 'Education',
    icon: '../assets/images/categories/education.png',
    showSubCategories: false,
    subCategories: [
      'Self-help books',
      'Theses abstracts',
      'International Conferences and Symposiums',
    ],
  },
  {
    name: 'Design',
    icon: '../assets/images/categories/design.png',
    showSubCategories: false,
    subCategories: [
      'Design: Architecture',
      'Web-design',
      'Construction: Renovation and interior design',
      'Construction: Renovation and interior design: Saunas',
    ],
  },
  {
    name: 'Psychology',
    icon: '../assets/images/categories/psychology.png',
    showSubCategories: false,
    subCategories: [
      'Creative Thinking',
      'The art of communication',
      'Neuro-Linguistic Programming',
    ],
  },
  {
    name: 'Techniques',
    icon: '../assets/images/categories/techniques.png',
    showSubCategories: false,
    subCategories: [
      'Automation',
      'Communication',
      'Electronics',
      'Energy',
      'Safety and Security',
      'Nanotechnology',
    ],
  },
  {
    name: 'Physics',
    icon: '../assets/images/categories/physics.png',
    showSubCategories: false,
    subCategories: [
      'Crystal Physics',
      'Geophysics',
      'Physics of lasers',
      'Plasma Physics',
      'Quantum Physics',
      'Theory of Relativity and Gravitation',
    ],
  },
];
